

tournaments = {
  "tour de france": "tourdefrance",
  "us open": "usopen",
  "us masters": "usmasters",
  "nfl" : "nfl",
  "dm" : "dm",
  "fifa vm" : "fifavm",
  "vm" : "vm",
  "em" : "em",
  "ryder cup" : "rydercup",
  "champions league" :  "championsleague",
  "ol": "ol",
  "nba" :"nba",
  "vuelta de españa" : "vuelta",
  "vuelta a españa" : "vuelta",
  "vuelta" : "vuelta",
  "vueltaen" : "vuelta",
  "atp turneringen" : "ATP",
  "atp 250-turneringen" : "ATP",
  "atp 1000-turneringen" : "ATP",
  "atp 5000-turneringen" : "ATP",
  "grandprix" : "grandprix",
  "grand prix" : "grandprix",
  "davis cup" : "daviscup",
  "ufc": "ufc",
  "mma" : "mma",
  "china open" : "chinaopen",
  "fiba europe cup" : "fiba",
  "wta" : "wta",
  "pga majoren": "pga",
  "europa league" : "europaleague",
  "european games" : "europeangames",
  "china open" : "chinaopen",
  "premier league" : "premierleague",
  "arctic open" : "arcticopen",
  "le mans" : "lemans",
  "lombardiet rundt" : "lombardietrundt",
  "shanghai open" : "shanghaiopen",
  "pga tour" : "pgatour",
  "pga" : "pgatour",
  "european Games" : "europeangames",
  "lpga tour" : "lpga",
  "european tour" : "europeantour",
  "super bowl": "superbowl",
  "atp" : "atp",
  "masters" : "masters",
  "bmw international open" : "bmwopen",
  "super g" : "superg",
  "grand slam": "gramslam",
  "wimbledon": "wimbledom",
  "superliga" : "superliga",
  "world cup" : "worldcup",
  "world series" : "worldseries",
  "hopman cup" : "hopmancup",
  "solheim cup" : "solheimcup",
  "fed cup" : "fedcup",
  "euro cup": "eurocup",
  "stanley cup" : "stanleycup" ,
  "super cup" : "supercup",
  "denmark open" : "denmarkopen",
  "mls" : "mls",
  "bundesliga" : "bundesliga",
  "major league" : "majorleague",
  "major" : "major",
  "french open":  "frenchopen",
  "champions cup" : "championscup",
  "pokalturnering" : "pokalturnering",
  "turnering": "turnering",
  "post danmark rundt": "postdanmarkrundt",
  "nhl" : "nhl",
  "powerman" : "powerman",
  "australian open" : "australienopen",
  "iem cologne" : "iemcologne",
  "stockholm open": "stockholm open",
  "uefa nations league" : "uefa",
  "nations league" : "nationsleague",
  "challenge tour" : "challengetour",
  "round denmark race" : "rounddenmarkrace",
  "liv golf": "livgolf",
  "fedex cup" :"fedexcup",
  "handa world international" : "handaworldinternational",
  "czech ladies open" : "czechladiesopen",
  "british open" : "britishopen",
  "british masters" : "britishmasters",
  "corales puntacana championship" : "coralespuntacanachampionship",
  "lpga tour" : "lpgatour",
  "mallorca golf open" : "mallorcagolfopen",
  "beijing 2022" : "beijing2022",
  "metal ligaen" : "metalliagen",
  "liv golf" : "livholf",
  "sudirman cup": "sudirmancup" 
}


weekdays = [
    "mandag",
    "tirsdag",
    "onsdag",
    "torsdag",
    "fredag",
    "lørdag",
    "søndag",
    "januar",
    "februar",
    "marts",
    "april",
    "maj",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "december"
]

# TODO : split til  weekdays of months

word_generalization = [ "xnumber", "xland", "xtournament", "xnationality", "xweekday", "xfinale", "xyear"]

non_alpha = [":", ",", "'", ".", "?", "!", '"']